### ISSUE TITLE
Too perfect

### ISSUE THREAD

**Issue by patheticGeek** [samuelkraft/samuelkraft-next#25]
A personal site isn't allowed to be so simple, elegant and beautiful.

P.S.: loving the look too much, so you mind if i steal it with credits?

**Comment by samuelkraft** [comment]
Haha thank you, I wish all bug tickets looked like this 😅

This site is published under a [MIT license](https://github.com/samuelkraft/samuelkraft-next/blob/master/LICENSE), so you are free to do whatever you wish as long as you preserve the license. That said, I'd appreciate if you give credit and link back to my site or this repo for any parts you might use.
